import Laptop1 from "./data_content/Laptop1.webp";
import Laptop2 from "./data_content/Laptop2.webp";
import Laptop3 from "./data_content/Laptop3.webp";
import Laptop4 from "./data_content/Laptop4.webp";
import Laptop5 from "./data_content/Laptop5.webp";
import Laptop6 from "./data_content/Laptop6.webp";

import Mobile1 from "./data_content/Mobile1.webp";
import Mobile2 from "./data_content/Mobile2.webp";
import Mobile3 from "./data_content/Mobile3.webp";
import Mobile4 from "./data_content/mobile4.webp";
import Mobile5 from "./data_content/mobile5.webp";
import Mobile6 from "./data_content/mobile6.webp";

import Keyboard1 from "./data_content/Keyboard1.webp";
import Keyboard2 from "./data_content/Keyboard2.webp";
import Keyboard3 from "./data_content/Keyboard3.webp";
import Keyboard4 from "./data_content/keyboard.4webp.webp";
import Keyboard5 from "./data_content/keyboard5.webp";
import Keyboard6 from "./data_content/keyboard6.webp";

import Mouse1 from "./data_content/Mouse1.webp";
import Mouse2 from "./data_content/Mouse2.webp";
import Mouse3 from "./data_content/Mouse3.webp";
import Mouse4 from "./data_content/mouse4.webp";
import Mouse5 from "./data_content/mouse5webp.webp";
import Mouse6 from "./data_content/mouse6.webp";

const data = [
  // ---------- Laptops ----------
  {
    id: "1",
    name: "HP Pavilion 15",
    price: 75000,
    image: Laptop1,
    company: "HP",
    description: "The HP Pavilion 15 offers a sleek design...",
    category: "laptop",
    shipping: true,
    amount: 1,
    stock: 4,
    bestSeller: true,
  },
  {
    id: "2",
    name: "HP Envy x360",
    price: 98000,
    image: Laptop2,
    company: "HP",
    description: "The HP Envy x360 is a 2-in-1 convertible laptop...",
    category: "laptop",
    shipping: true,
    amount: 1,
    stock: 6,
  },
  {
    id: "3",
    name: "HP Spectre x360",
    price: 125000,
    image: Laptop3,
    company: "HP",
    description: "The Spectre x360 is a premium ultrabook...",
    category: "laptop",
    shipping: true,
    amount: 1,
    stock: 4,
    bestSeller: true,
  },
  {
    id: "13",
    name: "Dell Inspiron 14",
    price: 78000,
    image: Laptop4,
    company: "Dell",
    description: "Dell Inspiron 14 is a versatile laptop...",
    category: "laptop",
    shipping: true,
    amount: 1,
    stock: 5,
  },
  {
    id: "14",
    name: "Asus Vivobook S15",
    price: 88000,
    image: Laptop5,
    company: "Asus",
    description: "The Asus Vivobook S15 comes with a vibrant OLED display...",
    category: "laptop",
    shipping: true,
    amount: 1,
    stock: 3,
  },
  {
    id: "15",
    name: "Lenovo IdeaPad Slim 5",
    price: 72000,
    image: Laptop6,
    company: "Lenovo",
    description: "Lenovo IdeaPad Slim 5 offers Ryzen 7 processor...",
    category: "laptop",
    shipping: true,
    amount: 1,
    stock: 4,
  },

  // ---------- Mice ----------
  {
    id: "4",
    name: "Logitech M330 Silent Plus",
    price: 70,
    image: Mouse1,
    company: "Logitech",
    description: "Ultra-quiet wireless mouse with ergonomic design.",
    category: "mouse",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: "5",
    name: "Razer DeathAdder Essential",
    price: 80,
    image: Mouse2,
    company: "Razer",
    description: "Gaming mouse with 6400 DPI sensor.",
    category: "mouse",
    shipping: true,
    amount: 1,
    stock: 4,
    bestSeller: true,
  },
  {
    id: "6",
    name: "Dell MS116 Optical Mouse",
    price: 20,
    image: Mouse3,
    company: "Dell",
    description: "Reliable wired mouse with 1000 DPI.",
    category: "mouse",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: "22",
    name: "HP X1000 Wired Mouse",
    price: 18,
    image: Mouse4,
    company: "HP",
    description: "Stylish wired mouse with optical sensor.",
    category: "mouse",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: "23",
    name: "Fantech UX1 Hero Gaming Mouse",
    price: 85,
    image: Mouse5,
    company: "Fantech",
    description: "High-DPI RGB gaming mouse with ergonomic grip.",
    category: "mouse",
    shipping: true,
    amount: 1,
    stock: 3,
    bestSeller: true,
  },
  {
    id: "24",
    name: "A4Tech N-70FX Wired Mouse",
    price: 22,
    image: Mouse6,
    company: "A4Tech",
    description: "Ergonomic wired mouse with optical sensor.",
    category: "mouse",
    shipping: true,
    amount: 1,
    stock: 5,
  },

  // ---------- Keyboards ----------
  {
    id: "7",
    name: "Logitech K380 Bluetooth Keyboard",
    price: 40,
    image: Keyboard1,
    company: "Logitech",
    description: "Compact multi-device Bluetooth keyboard.",
    category: "keyboard",
    shipping: true,
    amount: 1,
    stock: 2,
    bestSeller: true,
  },
  {
    id: "8",
    name: "Redragon K552 Kumara RGB",
    price: 90,
    image: Keyboard2,
    company: "Redragon",
    description: "RGB mechanical keyboard with red switches.",
    category: "keyboard",
    shipping: true,
    amount: 1,
    stock: 3,
  },
  {
    id: "9",
    name: "HP KM300F Combo Keyboard",
    price: 100,
    image: Keyboard3,
    company: "HP",
    description: "Full-size membrane keyboard with included mouse.",
    category: "keyboard",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: "19",
    name: "A4Tech KR-85",
    price: 25,
    image: Keyboard4,
    company: "A4Tech",
    description: "Durable wired keyboard, spill-resistant.",
    category: "keyboard",
    shipping: true,
    amount: 1,
    stock: 5,
  },
  {
    id: "20",
    name: "Fantech MK884 Optilux RGB",
    price: 85,
    image: Keyboard5,
    company: "Fantech",
    description: "Mechanical RGB keyboard with blue switches.",
    category: "keyboard",
    shipping: true,
    amount: 1,
    stock: 2,
  },
  {
    id: "21",
    name: "Logitech MK270 Wireless Combo",
    price: 60,
    image: Keyboard6,
    company: "Logitech",
    description: "Wireless keyboard and mouse combo with long battery life.",
    category: "keyboard",
    shipping: true,
    amount: 1,
    stock: 4,
    bestSeller: true,
  },

  // ---------- Mobiles ----------
  {
    id: "10",
    name: "Samsung Galaxy A13",
    price: 20000,
    image: Mobile1,
    company: "Samsung",
    description: "6.6-inch FHD+ display, 50MP camera, 5000mAh battery.",
    category: "mobile",
    shipping: true,
    amount: 1,
    stock: 5,
  },
  {
    id: "11",
    name: "Redmi Note 11",
    price: 22000,
    image: Mobile2,
    company: "Xiaomi",
    description: "6.43-inch AMOLED display, 50MP camera, Snapdragon 680.",
    category: "mobile",
    shipping: true,
    amount: 1,
    stock: 5,
    bestSeller: true,
  },
  {
    id: "12",
    name: "Realme Narzo 50A",
    price: 18000,
    image: Mobile3,
    company: "Realme",
    description: "6000mAh battery, 50MP camera, MediaTek G85.",
    category: "mobile",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: "16",
    name: "iPhone 13",
    price: 90000,
    image: Mobile4,
    company: "Apple",
    description: "iPhone 13 with A15 Bionic chip and dual-camera.",
    category: "mobile",
    shipping: true,
    amount: 1,
    stock: 2,
    bestSeller: true,
  },
  {
    id: "17",
    name: "Samsung Galaxy S22",
    price: 95000,
    image: Mobile5,
    company: "Samsung",
    description: "Flagship phone with AMOLED 2X display and Snapdragon 8 Gen 1.",
    category: "mobile",
    shipping: true,
    amount: 1,
    stock: 3,
  },
  {
    id: "18",
    name: "OnePlus Nord CE 2 Lite",
    price: 28000,
    image: Mobile6,
    company: "OnePlus",
    description: "6.59-inch 120Hz display, 64MP camera, 5000mAh battery.",
    category: "mobile",
    shipping: true,
    amount: 1,
    stock: 4,
  },
];

export default data;
